pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick

/**
 * Tutorial copy lives separately from the metadata registry.  This keeps the
 * registry a stable index for cards/deep links while allowing the long-form
 * guide to grow without duplicating service integration rules.
 */
QtObject {
    function contentFor(contentId: string): var {
        if (contentId === "gmail") {
            return ({
                "intro": "Use the existing Gmail cheatsheet flow to add an account and choose the mail surfaces you want in II.",
                "prerequisites": [
                    "A Gmail account and the client credentials required by the existing Cheatsheet flow."
                ],
                "steps": [
                    {
                        "title": "Open the Gmail setup",
                        "body": "The Cheatsheet's Gmail page is the source of truth for credentials and OAuth. Welcome does not copy its setup steps or create a second flow.",
                        "actionLabel": "Open Gmail settings",
                        "actionPage": "cheatSheet"
                    },
                    {
                        "title": "Complete the current Cheatsheet flow",
                        "body": "Follow the live Gmail instructions there, authenticate in your browser, then return to II. The page remains the single source of truth as the flow evolves.",
                        "actionLabel": "Continue in Settings",
                        "actionPage": "cheatSheet"
                    }
                ],
                "verification": [
                    "The Gmail card reports Ready after authentication.",
                    "The cheatsheet can display a recent inbox without an error."
                ],
                "troubleshooting": [
                    "If credentials are missing, use the setup instructions in the Cheatsheet and reopen that page.",
                    "Configured credentials and an authenticated session are separate states; authenticate again if the card says Continue."
                ]
            });
        }

        if (contentId === "ticktick") {
            return ({
                "intro": "TickTick sync is optional. Add credentials through Accounts & Backup, then let the existing TickTick service handle refreshes.",
                "prerequisites": [
                    "A TickTick developer application with its client ID and secret.",
                    "A TickTick access token generated by the existing settings flow."
                ],
                "steps": [
                    {
                        "title": "Open Accounts & Backup",
                        "body": "Use the existing credentials form instead of entering tokens in Welcome.",
                        "actionLabel": "Open account settings",
                        "actionPage": "tasksAccounts"
                    },
                    {
                        "title": "Save the TickTick credentials",
                        "body": "Paste the client ID, client secret and access token, then save. The service reads the stored values and exposes its current state to Welcome.",
                        "actionLabel": "Continue in Settings",
                        "actionPage": "tasksAccounts"
                    },
                    {
                        "title": "Review the task behavior",
                        "body": "Return to the tasks options to choose how TickTick appears beside local tasks. No sync starts from this tutorial.",
                        "actionLabel": "Review task options",
                        "actionPage": "tasksAccounts"
                    }
                ],
                "verification": [
                    "The TickTick card reports Ready when an access token is present.",
                    "The task widget can load your inbox after the service's normal refresh."
                ],
                "troubleshooting": [
                    "If the card says Continue, verify that the access token was saved in Accounts & Backup.",
                    "A token can be present while a request is syncing; wait for the service status to settle before diagnosing the account."
                ]
            });
        }

        if (contentId === "calendar") {
            return ({
                "intro": "Google Calendar in II uses the local khal calendar database and vdirsyncer. Configure those tools once, then let CalendarService read the result.",
                "prerequisites": [
                    "khal and vdirsyncer installed on the system.",
                    "A calendar provider configured in vdirsyncer and khal."
                ],
                "steps": [
                    {
                        "title": "Install the calendar tools",
                        "body": "Install khal and vdirsyncer with your distribution package manager if they are not already present.",
                        "command": "khal --version && vdirsyncer --version"
                    },
                    {
                        "title": "Configure the provider",
                        "body": "Create the vdirsyncer collection and point khal at the synchronized calendar directory. Keep provider credentials in the tools' normal config files.",
                        "command": "vdirsyncer discover"
                    },
                    {
                        "title": "Synchronize before opening the calendar",
                        "body": "Run a manual sync from a terminal, then return to II. Welcome only reads the existing service state and never starts a sync automatically.",
                        "command": "vdirsyncer sync"
                    }
                ],
                "verification": [
                    "The Calendar card reports Ready when the existing khal probe succeeds.",
                    "The calendar widget shows events from the local khal database."
                ],
                "troubleshooting": [
                    "A failed khal probe may mean the database is empty or the provider is not configured; it is not a complete package-manager detector.",
                    "Run vdirsyncer sync manually and then restart the calendar surface if the local database has no events."
                ]
            });
        }

        if (contentId === "drive") {
            return ({
                "intro": "Google Drive backups reuse the existing rclone service and Gmail client credentials. Configure them in Accounts & Backup, then choose what II should back up.",
                "prerequisites": [
                    "rclone installed and available in PATH.",
                    "Gmail OAuth client credentials available in ii/.env."
                ],
                "steps": [
                    {
                        "title": "Open Accounts & Backup",
                        "body": "The settings page owns rclone setup, OAuth hand-off and backup preferences.",
                        "actionLabel": "Open backup settings",
                        "actionPage": "tasksAccounts"
                    },
                    {
                        "title": "Authorize the Drive remote",
                        "body": "Use the existing rclone setup action. Welcome does not call rclone or duplicate the OAuth process.",
                        "actionLabel": "Continue in Settings",
                        "actionPage": "tasksAccounts"
                    },
                    {
                        "title": "Choose folders and schedule",
                        "body": "Select the II data folders, retention and schedule that you want. Start the first backup from Settings when you are ready.",
                        "actionLabel": "Review backup options",
                        "actionPage": "tasksAccounts"
                    }
                ],
                "verification": [
                    "The Drive card reports Ready when rclone is installed and a remote is configured.",
                    "Accounts & Backup shows the selected folders and latest backup status."
                ],
                "troubleshooting": [
                    "If rclone is missing, install it first and return to Accounts & Backup so the existing checker can update.",
                    "If OAuth credentials are missing, verify the Gmail client values in ii/.env; the Drive service intentionally reuses them."
                ]
            });
        }

        return ({
            "intro": "This tutorial is not available yet.",
            "prerequisites": [],
            "steps": [],
            "verification": [],
            "troubleshooting": []
        });
    }
}
