pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common
import qs.modules.common.functions

/**
 * Typed, local access to the Settings index.
 *
 * The index is generated by scripts/ai/ai_settings_index.py so QML never has
 * to parse every Settings page on the hot path. This adapter owns only the
 * Settings DTO/validation
 * boundary; views and AI providers consume its small objects and never touch
 * config.json as a blob.
 */
QtObject {
    id: root

    readonly property string indexPath: FileUtils.trimFileProtocol(`${Directories.state}/user/ai/settings_index.json`)
    readonly property string generatorPath: Directories.aiSettingsIndexScriptPath
    property var index: ({ schema: 0, entries: [] })
    property bool ready: false
    property bool rebuilding: false
    property string lastError: ""

    readonly property var entries: Array.from(root.index?.entries ?? [])

    function ensureIndex() {
        if (root.rebuilding || indexCheck.running)
            return;
        indexCheck.running = true;
    }

    function rebuild() {
        if (root.rebuilding)
            return;
        root.rebuilding = true;
        root.ready = false;
        indexBuild.running = true;
    }

    function ingest(raw: string) {
        try {
            const parsed = JSON.parse(raw);
            if (!Array.isArray(parsed?.entries))
                throw new Error("entries are missing");
            root.index = parsed;
            root.ready = true;
            root.lastError = "";
        } catch (error) {
            root.ready = false;
            root.lastError = String(error);
        }
    }

    function entryFor(key: string): var {
        const wanted = String(key ?? "");
        return root.entries.find(entry => String(entry?.key ?? "") === wanted) ?? null;
    }

    function currentValue(key: string): var {
        return Config.getNestedValue(Config.options, String(key).split("."));
    }

    function settingRef(entry: var, score = 0): var {
        if (!entry)
            return null;
        const ref = Object.assign({}, entry);
        ref.currentValue = root.currentValue(entry.key);
        ref.score = Number(score);
        return ref;
    }

    function tokens(value: string): var {
        return String(value ?? "").toLocaleLowerCase().normalize("NFD")
            .replace(/[\u0300-\u036f]/g, "")
            .split(/[^\p{L}\p{N}_]+/u)
            .filter(token => token.length > 1);
    }

    function search(query: string, limit = 8): var {
        const normalized = String(query ?? "").trim().toLocaleLowerCase();
        const queryTokens = root.tokens(normalized);
        if (queryTokens.length === 0)
            return [];
        const results = [];
        for (const entry of root.entries) {
            const label = String(entry.label ?? "").toLocaleLowerCase();
            const localLabel = String(entry.labelLocalized ?? "").toLocaleLowerCase();
            const key = String(entry.key ?? "").toLocaleLowerCase();
            const lastKey = key.split(".").at(-1) ?? "";
            const description = `${entry.description ?? ""} ${entry.descriptionLocalized ?? ""}`.toLocaleLowerCase();
            const navigation = `${Array.from(entry.aliases ?? []).join(" ")} ${entry.pageName ?? ""} ${entry.sectionTitle ?? ""} ${entry.sectionTitleLocalized ?? ""}`.toLocaleLowerCase();
            const keywords = Array.from(entry.keywords ?? []).map(word => String(word).toLocaleLowerCase());
            let score = entry.hasUi === true ? 40 : 0;
            for (const token of queryTokens) {
                if (token === label || token === localLabel)
                    score += 500;
                else if (label.startsWith(token) || localLabel.startsWith(token))
                    score += 200;
                if (lastKey === token || root.tokens(lastKey).indexOf(token) >= 0)
                    score += 180;
                if (description.indexOf(token) >= 0)
                    score += 120;
                if (navigation.indexOf(token) >= 0)
                    score += 100;
                if (keywords.indexOf(token) >= 0)
                    score += 90;
            }
            if (score > (entry.hasUi === true ? 40 : 0))
                results.push(root.settingRef(entry, score));
        }
        return results.sort((left, right) => Number(right.score) - Number(left.score)).slice(0, Math.max(1, Math.min(8, Number(limit) || 8)));
    }

    function get(keys: var): var {
        const wanted = Array.from(keys ?? []).slice(0, 10);
        return wanted.map(key => {
            const entry = root.entryFor(String(key));
            if (!entry)
                return { key: String(key), error: "unknownKey" };
            return root.settingRef(entry);
        });
    }

    function validate(key: string, value: var): var {
        const entry = root.entryFor(key);
        if (!entry)
            return { ok: false, reason: "unknownKey" };
        const type = String(entry.type ?? "unknown");
        if (type === "bool" && typeof value !== "boolean")
            return { ok: false, reason: "expectedBool" };
        if (type === "int" && (typeof value !== "number" || !Number.isInteger(value)))
            return { ok: false, reason: "expectedInteger" };
        if (type === "real" && (typeof value !== "number" || !Number.isFinite(value)))
            return { ok: false, reason: "expectedNumber" };
        if (type === "string" && typeof value !== "string")
            return { ok: false, reason: "expectedString" };
        if (type === "enum") {
            const options = Array.from(entry.options ?? []).map(option => option.value);
            if (options.length > 0 && options.indexOf(value) < 0)
                return { ok: false, reason: "outsideOptions" };
        }
        const range = entry.range ?? null;
        if (range && typeof value === "number") {
            if (range.from !== null && range.from !== undefined && value < Number(range.from))
                return { ok: false, reason: "belowRange" };
            if (range.to !== null && range.to !== undefined && value > Number(range.to))
                return { ok: false, reason: "aboveRange" };
            const step = Number(range.step ?? 0);
            if (step > 0 && range.from !== null && range.from !== undefined
                    && Math.abs(((value - Number(range.from)) / step) - Math.round((value - Number(range.from)) / step)) > 0.000001)
                return { ok: false, reason: "outsideStep" };
        }
        try {
            const strict = Config.validateNestedValue(key, value);
            if (strict?.ok === false)
                return strict;
        } catch (error) {
            return { ok: false, reason: String(error) };
        }
        return { ok: true, reason: "", value: value, entry: entry };
    }

    function propose(changes: var): var {
        const preview = [];
        const warnings = [];
        for (const change of Array.from(changes ?? [])) {
            const key = String(change?.key ?? "");
            const verdict = root.validate(key, change?.value);
            const entry = verdict.entry ?? root.entryFor(key);
            const item = {
                key: key,
                label: entry?.labelLocalized ?? entry?.label ?? key,
                current: root.currentValue(key),
                proposed: change?.value,
                valid: verdict.ok === true,
                reason: verdict.reason ?? "",
                requiresRestart: entry?.requiresRestart === true
            };
            if (entry?.dependsOn && root.currentValue(entry.dependsOn) !== true) {
                item.dependencyWarning = entry.dependsOn;
                warnings.push(`${key} depends on ${entry.dependsOn}`);
            }
            if (item.requiresRestart)
                warnings.push(`${key} requires restart`);
            preview.push(item);
        }
        return { changes: preview, warnings: warnings, requiresRestart: preview.some(change => change.requiresRestart) };
    }

    function apply(changes: var): var {
        const applied = [];
        const skipped = [];
        for (const change of Array.from(changes ?? [])) {
            const key = String(change?.key ?? "");
            const value = change?.proposed !== undefined ? change.proposed : change?.value;
            const verdict = root.validate(key, value);
            if (!verdict.ok) {
                skipped.push({ key: key, reason: verdict.reason });
                continue;
            }
            try {
                Config.setNestedValue(key, value, true);
                applied.push({ key: key, value: value });
            } catch (error) {
                skipped.push({ key: key, reason: String(error) });
            }
        }
        return { applied: applied, skipped: skipped };
    }

    readonly property FileView indexFile: FileView {
        id: indexFile
        path: root.indexPath
        watchChanges: true
        printErrors: false
        onLoaded: root.ingest(text())
        onLoadFailed: root.rebuild()
    }

    readonly property Process indexCheck: Process {
        id: indexCheck
        command: ["python3", root.generatorPath, "--out", root.indexPath, "check"]
        onExited: exitCode => {
            if (exitCode === 0)
                indexFile.reload();
            else
                root.rebuild();
        }
    }

    readonly property Process indexBuild: Process {
        id: indexBuild
        command: ["python3", root.generatorPath, "--out", root.indexPath, "build"]
        onExited: exitCode => {
            root.rebuilding = false;
            if (exitCode === 0)
                indexFile.reload();
            else
                root.lastError = "settings index build failed";
        }
    }

    Component.onCompleted: root.ensureIndex()
}
